#ifndef QuantoGraph_h
#define QuantoGraph_h

#include <Arduino.h>

#include "./Music/Misc.h"
#include "./Music/MidiFile.h"
#include "./Music/Note.h"
#include "./Music/Track.h"
#include "./Music/Song.h"
#include "./Music/Fingers.h"
#include "./Music/Staff.h"
#include "./Music/Keys.h"
#include "./Music/Effects.h"
#include "./Music/Synth.h"

#include "./Devices/AudioBoard.h"
#include "./Devices/AudioInput.h"
#include "./Devices/Bluetooth.h"
//#include "./Devices/CapSensor.h"
#include "./Devices/Led.cpp"
#include "./Devices/Led.h"
//#include "./Devices/MidiChip.h"
#include "./Devices/MidiInput.h"
//#include "./Devices/Motion.h"
#include "./Devices/SdCard.h"
#include "./Devices/TouchScreen.h"

#include "./Sound/bassoon_samples.h"
#include "./Sound/clarinet_samples.h"
#include "./Sound/distortiongt_samples.h"
#include "./Sound/drumBass_samples.h"
#include "./Sound/drumBlock_samples.h"
#include "./Sound/drumCrash_samples.h"
#include "./Sound/drumHat_samples.h"
#include "./Sound/drumRide_samples.h"
#include "./Sound/drumSnare_samples.h"
#include "./Sound/drumTomHigh_samples.h"
#include "./Sound/drumTomLow_samples.h"
#include "./Sound/epiano_samples.h"
#include "./Sound/flute_samples.h"
#include "./Sound/frenchhorn_samples.h"
#include "./Sound/glockenspiel_samples.h"
#include "./Sound/gtfretnoise_samples.h"
#include "./Sound/harmonica_samples.h"
#include "./Sound/harp_samples.h"
#include "./Sound/mutedgtr_samples.h"
#include "./Sound/nylonstrgtr_samples.h"
#include "./Sound/oboe_samples.h"
#include "./Sound/overdrivegt_samples.h"
#include "./Sound/piano_samples.h"
#include "./Sound/recorder_samples.h"
#include "./Sound/standard_DRUMS_samples.h"
#include "./Sound/steelstrgtr_samples.h"
#include "./Sound/strings_samples.h"
#include "./Sound/timpani_samples.h"
#include "./Sound/trombone_samples.h"
#include "./Sound/trumpet_samples.h"
#include "./Sound/tuba_samples.h"
#include "./Sound/vibraphone_samples.h"

#endif
